MvcApplication3/Controllers/CargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication3.Models;
using System.Data.SqlClient;

namespace MvcApplication3.Controllers
{
    public class CargoController : Controller
    {
        //
        // GET: /Cargo/

        bd_escuelaEntities bd = new bd_escuelaEntities();

        public ActionResult Index()
        {
            var listaCargos = bd.CARGO;
            return View(listaCargos.ToList());
        }

        public ActionResult ListadoMaestraCargos(){
            var listaCargos = bd.CARGO;
            return View(listaCargos.ToList());
        }

        public ActionResult UsuarioPorCargo(string cargoStr) {
            string Query = "SELECT u.codigo_usuario, u.nomusuario, u.codigo_cargo FROM USUARIO u, CARGO c WHERE u.codigo_cargo = c.codigo_cargo AND c.descripcion = @cargoP";
            SqlParameter param = new SqlParameter("cargoP", cargoStr);
            object[] sqlParam = new object[] { param };
            var modelo = bd.USUARIO.SqlQuery(Query, sqlParam);
            return View(modelo.ToList());
        }

        public ActionResult ListadoUsuarioConDescripcionCargo(){
            var modelo = from u in bd.USUARIO
                         join c in bd.CARGO
                            on u.codigo_cargo equals c.codigo_cargo
                         select new UsuarioModel
                         {
                             codigo = u.codigo_usuario,
                             nomusuario = u.nomusuario,
                             cargo = c.descripcion
                         };
            return View(modelo.ToList());
        }
    }
}

MvcApplication3/Controllers/MntCargosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication3.Models;

namespace MvcApplication3.Controllers
{
    public class MntCargosController : Controller
    {
        private bd_escuelaEntities db = new bd_escuelaEntities();

        //
        // GET: /MntCargos/

        public ActionResult Index()
        {
            return View(db.CARGO.ToList());
        }

        //
        // GET: /MntCargos/Details/5

        public ActionResult Details(int id = 0)
        {
            CARGO cargo = db.CARGO.Find(id);
            if (cargo == null)
            {
                return HttpNotFound();
            }
            return View(cargo);
        }

        //
        // GET: /MntCargos/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /MntCargos/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CARGO cargo)
        {
            if (ModelState.IsValid)
            {
                db.CARGO.Add(cargo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cargo);
        }

        //
        // GET: /MntCargos/Edit/5

        public ActionResult Edit(int id = 0)
        {
            CARGO cargo = db.CARGO.Find(id);
            if (cargo == null)
            {
                return HttpNotFound();
            }
            return View(cargo);
        }

        //
        // POST: /MntCargos/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CARGO cargo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cargo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cargo);
        }

        //
        // GET: /MntCargos/Delete/5

        public ActionResult Delete(int id = 0)
        {
            CARGO cargo = db.CARGO.Find(id);
            if (cargo == null)
            {
                return HttpNotFound();
            }
            return View(cargo);
        }

        //
        // POST: /MntCargos/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CARGO cargo = db.CARGO.Find(id);
            db.CARGO.Remove(cargo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication3/Controllers/MntoUsuariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication3.Models;

namespace MvcApplication3.Controllers
{
    public class MntoUsuariosController : Controller
    {
        private bd_escuelaEntities db = new bd_escuelaEntities();

        //
        // GET: /MntoUsuarios/

        public ActionResult Index()
        {
            var usuario = db.USUARIO.Include(u => u.CARGO);
            return View(usuario.ToList());
        }

        //
        // GET: /MntoUsuarios/Details/5

        public ActionResult Details(int id = 0)
        {
            USUARIO usuario = db.USUARIO.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        //
        // GET: /MntoUsuarios/Create

        public ActionResult Create()
        {
            ViewBag.codigo_cargo = new SelectList(db.CARGO, "codigo_cargo", "descripcion");
            return View();
        }

        //
        // POST: /MntoUsuarios/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(USUARIO usuario)
        {
            if (ModelState.IsValid)
            {
                db.USUARIO.Add(usuario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.codigo_cargo = new SelectList(db.CARGO, "codigo_cargo", "descripcion", usuario.codigo_cargo);
            return View(usuario);
        }

        //
        // GET: /MntoUsuarios/Edit/5

        public ActionResult Edit(int id = 0)
        {
            USUARIO usuario = db.USUARIO.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            ViewBag.codigo_cargo = new SelectList(db.CARGO, "codigo_cargo", "descripcion", usuario.codigo_cargo);
            return View(usuario);
        }

        //
        // POST: /MntoUsuarios/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(USUARIO usuario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(usuario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.codigo_cargo = new SelectList(db.CARGO, "codigo_cargo", "descripcion", usuario.codigo_cargo);
            return View(usuario);
        }

        //
        // GET: /MntoUsuarios/Delete/5

        public ActionResult Delete(int id = 0)
        {
            USUARIO usuario = db.USUARIO.Find(id);
            if (usuario == null)
            {
                return HttpNotFound();
            }
            return View(usuario);
        }

        //
        // POST: /MntoUsuarios/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            USUARIO usuario = db.USUARIO.Find(id);
            db.USUARIO.Remove(usuario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Mi aplicación ASP.NET MVC</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Prueba GT", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    @*<section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>*@
                    <nav>
                        <ul id="menu">
                           @* <li>@Html.ActionLink("Inicio", "Index", "Home")</li>*@
                            <li>@Html.ActionLink("Listado de cargos", "Index", "Cargo")</li>
                          @*  <li>@Html.ActionLink("Lista maestra de cargos", "ListaMaestraCargos", "Cargo")</li>*@
                            <li>@Html.ActionLink("Usuarios con cargo", "ListadoUsuarioConDescripcionCargo", "Cargo")</li>
                            <li>@Html.ActionLink("Mantenimiento cargos", "Index", "MntCargos")</li>
                            <li>@Html.ActionLink("Mantenimiento usuarios", "Index", "MntoUsuarios")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET MVC</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>